In [ ]:
class MyClass:
  x = 5
p1 = MyClass() #Created p1, which is an object of class type MyClass
print(p1.x) 

5


In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name #p1.name = name
    self.age = age #p1.age = age
  def myfunc(self):
    print("Hello my name is " + self.name) #p1.name

p1 = Person("John", 12)
p2 = Person("elon", 71)
p3 = Person("smol", 43)
print(p1.name)
print(p1.age)
p1.myfunc()

John
12
Hello my name is John


In [ ]:
class showInfo(object):
    'Initialize a classL'
    def __init__(self, name, phone, age):
        self.name = name
        self.phone = phone
        self.age = age

    def showName(self):
        print("Name: "+self.name)

    def showAge(self):
        print("Age: "+self.age)

    def showPhone(self):
        print("Phone: "+self.phone)

emp1 = showInfo("Tom", "555-1212", 21)
emp1.showName()

Name: Tom


In [ ]:
#Inheritance
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname) #calls the Parent _init_
    self.graduationyear = year

x = Student("Mike", "JJ", 2019)
y = Person("Ashutosh", "Senapati")
x.printname()
y.printname()

Mike JJ
Ashutosh Senapati


In [ ]:
pwd

'/content'

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(b)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
a.ndim #number of dimensions

1

In [ ]:
b.ndim

2

In [ ]:
b.shape #dimensions

(2, 4)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#Code is getting confusing so I am going to comment lol. Comment Gang XD
import math
features = []
Y = []
for i in range(22): #Read Dataset
  features.append([])
print(len(features))
for line in open("agaricus-lepiota.data", "r"):
    values = line.split(",")
    Y.append(values[0])
    for i in range(22):
      features[i].append(values[(i + 1)])
def probability(inlist, value): #number of str x in list / length of list; Finds probability that you will pick x out of all of the values in the list
  occur = 0
  occur = sum(value in s for s in inlist)
  return occur/len(inlist)
entropy = lambda probY: 0-sum([math.log(probY), math.log(1-probY)]) #Finds the entropy given probability of event Y
print(f"The current entropy is: {entropy(probability(Y, 'p'))}")
def unique(li): # Finds the unique values of list "li"
  uniqueli = []
  for x in li:
    if x not in uniqueli:
      uniqueli.append(x)
  return uniqueli
uniquef = unique(features[0]) # The Distinct values in individual feature f
print(uniquef)
probX = []
def fprob(f): # Finds the probability of each occurunce of a unique value. IE: flat top, flat top, curved top, bell top: Uniquef = [f, c, b], probX = [1/2, 1/4, 1/4]
  probX = []
  for x in uniquef:
    probX.append(probability(features[f], x))
  return(probX)
def cond_prob(X, Y, value): # Finds the conditional probability of mushroom being edible given event value.
  pore = []
  for x in range(len(X)):
    if X[x] == value:
      pore.append(Y[x])
  poccur = sum('p' in s for s in pore)
  eoccur = sum('e' in s for s in pore)
  return eoccur/len(pore)
def log(x): # Log function but does NOT make STUPID ERRORS LIKE "domain value error". Instead, it returns 0 for log(0) like a PROPER function
  if x > 0:
    return math.log(x)
  else:
    return 0
fentropy = [] # List storing conditional entropy of each individual feature
cond_entropy = lambda pX, X: 0-sum([pX[i]*sum([cond_prob(X, Y, uniquef[i]) * log(cond_prob(X, Y, uniquef[i]))]) for i in range(len(probX))]) # conditional entropy function
for s in range(len(features)): # Calculates all conditional entropies of each feature
  uniquef = unique(features[s])
  probX = fprob(s)
  #print(f"unique features: {uniquef}, probabilitiesL {probX}")
  fentropy.append(cond_entropy(probX, features[s]))
  print(f"Cond_Entropy of Feature{s}: {cond_entropy(probX, features[s])}")
branch = 1
prev_branch = 0
while (branch == prev_branch) == False:#After 5, it just repeats itself
  branch = fentropy.index(min(fentropy))
  print(f"feature: {branch + 1}")
  uniquef = unique(features[branch])
  print(unique(features[branch]))
  probX = fprob(branch)
  branchd = [cond_prob(features[branch], Y, uniquef[i]) for i in range(len(probX))] # Branch Details
  print(branchd)
  prev_branch = branch
  del fentropy[branch]
  branch = fentropy.index(min(fentropy))
#branch = fentropy.index(min(fentropy))

22
The current entropy is: 1.387587087332604
['x', 'b', 's', 'f', 'k', 'c']
Cond_Entropy of Feature0: 0.32643182634649137
Cond_Entropy of Feature1: 0.3317213287113902
Cond_Entropy of Feature2: 0.3291736203469535
Cond_Entropy of Feature3: 0.2810740066972051
Cond_Entropy of Feature4: 0.01451694281595727
Cond_Entropy of Feature5: 0.33745038504835284
Cond_Entropy of Feature6: 0.3158355137205538
Cond_Entropy of Feature7: 0.24991734598012838
Cond_Entropy of Feature8: 0.17983715341365125
Cond_Entropy of Feature9: 0.3382045563101994
Cond_Entropy of Feature10: 0.3022489958875004
Cond_Entropy of Feature11: 0.2233773031479196
Cond_Entropy of Feature12: 0.22853596818531377
Cond_Entropy of Feature13: 0.2539894846673273
Cond_Entropy of Feature14: 0.26078801219616554
Cond_Entropy of Feature15: 0.34073983113413664
Cond_Entropy of Feature16: 0.3359567628915135
Cond_Entropy of Feature17: 0.3300993959006401
Cond_Entropy of Feature18: 0.21501926032856086
Cond_Entropy of Feature19: 0.1734570633980884
Cond_